name: StrangerChat
options:
  bundleIdPrefix: com.strangerchat
  deploymentTarget:
    iOS: "15.0"
  createIntermediateGroups: true
  createGroupForSourcesRoot: true

settings:
  base:
    INFOPLIST_FILE: StrangerChat/Info.plist
    DEVELOPMENT_TEAM: YOUR_TEAM_ID
    CODE_SIGN_STYLE: Automatic
    SWIFT_VERSION: "5.0"
    IPHONEOS_DEPLOYMENT_TARGET: "15.0"
    TARGETED_DEVICE_FAMILY: "1"
    VALID_ARCHS: "arm64"
    ENABLE_BITCODE: NO
    ENABLE_TESTABILITY: YES
    ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES

info:
  path: StrangerChat/Info.plist
  properties:
    CFBundleName: StrangerChat
    CFBundleIdentifier: com.strangerchat.app
    CFBundleVersion: 1.0
    CFBundleShortVersionString: 1.0
    UILaunchStoryboardName: LaunchScreen
    UIMainStoryboardFile: Main
    UIRequiredDeviceCapabilities:
      - armv7
    UISupportedInterfaceOrientations:
      - UIInterfaceOrientationPortrait
    LSRequiresIPhoneOS: true
    NSCameraUsageDescription: "需要访问相机以拍摄照片"
    NSPhotoLibraryUsageDescription: "需要访问相册以选择照片"
    NSMicrophoneUsageDescription: "需要访问麦克风以录制语音"
    NSLocationWhenInUseUsageDescription: "需要访问位置以提供附近的人功能"

projects:
  StrangerChat:
    type: application
    platform: iOS
    sources: ["Source/**/*"]
